{% set name = "discord.py" %}
{% set version = "2.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/discord_py-{{ version }}.tar.gz
  sha256: 59a2e1a3bee90d45ab2cee1abf2fefbb3f4ca5124cb4290702f08e6c54282f64

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - aiohttp >=3.7.4,<4

test:
  imports:
    - discord
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Rapptz/discord.py
  summary: A Python wrapper for the Discord API
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - galaxyonfire
