{% set name = "discord.py" %}
{% set version = "2.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/discord_py-{{ version }}.tar.gz
  sha256: 01cd362023bfea1a4a1d43f5280b5ef00cad2c7eba80098909f98bf28e578524

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - aiohttp >=3.7.4,<4

test:
  imports:
    - discord
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Rapptz/discord.py
  summary: A Python wrapper for the Discord API
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - galaxyonfire
