{% set name = "discord.py" %}
{% set version = "2.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/discord.py-{{ version }}.tar.gz
  sha256: f9df95795c6f52c5db43b7ab43634993e12ef233288636a759166dd9c134d077

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - aiohttp >=3.7.4,<4

test:
  imports:
    - discord
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Rapptz/discord.py
  summary: A Python wrapper for the Discord API
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - galaxyonfire
